apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-test
  namespace: default
spec:
  project: gitops-app
  source:
    repoURL: https://github.com/Dyhia777/argo-cd-project.git
    targetRevision: main
    path: my-argo-apps-child/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true