apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-test
  namespace: argo-cd
spec:
  project: gitops-app
  source:
    repoURL: https://github.com/Dyhia777/argo-cd-project.git
    targetRevision: main
    path: my-argo-apps-child
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated: null