apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argo-cd
spec:
  project: gitops-app
  source:
    repoURL: https://helm.elastic.co
    chart: elasticsearch
    targetRevision: 8.5.1
    helm:
      values: |
        pushgateway:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true